<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class WisataSeeder extends Seeder
{
    public function run()
    {
        $wisata = [
            ['nama_wisata' => 'Kawah Ijen', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 1, 'gambar' => 'kawah-ijen.jpeg', 'deskripsi' => null, 'jam_operasional' => '02.00-11.00', 'harga_tiket' => '30000', 'fasilitas' => 'Parkir, Toilet, Musholla, Tempat Makan, Penginapan', 'akses' => 'Motor, Mobil, Mobil Elf'],
            ['nama_wisata' => 'Kawah Wurung', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 1, 'gambar' => 'kawah_wurung.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '10000', 'fasilitas' => 'Parkir, Toilet, Penginapan, Tempat Makan', 'akses' => 'Motor, Mobil, Mobil Elf'],
            ['nama_wisata' => 'Pemandangan Arak-Arak', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 1, 'gambar' => 'arak_arak.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-17.00', 'harga_tiket' => '10000', 'fasilitas' => 'Parkir, Toilet, Musholla, Tempat Bermain, Tempat Makan, Spot Foto', 'akses' => 'Motor, Mobil, Mobil Elf, Bus'],
            ['nama_wisata' => 'Air Terjun Tancak Kembar', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 1, 'gambar' => 'tancak_kembar.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '10000', 'fasilitas' => 'Parkir, Toilet',  'akses' => 'Motor, Mobil'],
            ['nama_wisata' => 'Air Terjun Blawan', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 1, 'gambar' => 'air_terjun_blawan.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '10000', 'fasilitas' => 'Parkir, Toilet, Musholla',  'akses' => 'Motor, Mobil, Mobil Elf'],
            ['nama_wisata' => 'Aliran Asam Kali Pait', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 1, 'gambar' => 'kali_pait.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '0', 'fasilitas' => 'Parkir',  'akses' => 'Motor, Mobil, Mobil Elf'],
            ['nama_wisata' => 'Pemandian Air Panas Blawan', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 1, 'gambar' => 'air_panas_blawan.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '10000', 'fasilitas' => 'Parkir, Musholla, Toilet, Tempat Makan, Penginapan',  'akses' => 'Motor, Mobil, Mobil Elf'],
            ['nama_wisata' => "Taman Batu So'on Solor", 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 1, 'gambar' => 'taman_batu_soon.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '10000', 'fasilitas' => 'Parkir, Toilet, Musholla, Tempat Bermain, Tempat Makan, Spot Foto',  'akses' => 'Motor, Mobil, Mobil Elf'],
            ['nama_wisata' => 'Dinding Kaldera Ijen Megasari', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 1, 'gambar' => 'kaldera_megasari.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '10000', 'fasilitas' => 'Parkir, Toilet, Musholla',  'akses' => 'Motor'],
            ['nama_wisata' => 'Bosamba Rafting', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 1, 'gambar' => 'bosamba_rafting.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '175000', 'fasilitas' => 'Parkir, Gazebo, Musholla, Toile',  'akses' => 'Motor, Mobil, Mobil Elf'],
            ['nama_wisata' => 'Pendakian Gunung Raung', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 1, 'gambar' => 'gunung_raung.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '50000', 'fasilitas' => 'Parkir, Musholla, Papan Informasi, Penginapan',  'akses' => 'Motor, Mobil, Mobil Elf'],
            ['nama_wisata' => 'Hutan Pelangi', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 1, 'gambar' => 'hutan_pelangi.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '10000', 'fasilitas' => 'Papan Informasi',  'akses' => 'Motor, Mobil, Mobil Elf'],
            ['nama_wisata' => 'Aliran Lava Plalangan (Black Lava Planglangan)', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 1, 'gambar' => 'lava_plalangan.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '10000', 'fasilitas' => 'Parkir, Toilet, Musholla, Gazebo',  'akses' => 'Motor, Mobil, Mobil Elf'],
            ['nama_wisata' => 'Air Terjun Gentongan', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 1, 'gambar' => 'air_terjun_gentongan.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '0', 'fasilitas' => 'Papan Informasi',  'akses' => 'Motor, Mobil, Mobil Elf'],
            ['nama_wisata' => 'Lava blawan (Air terjun Litle Niagara Mini)', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 1, 'gambar' => 'lava_blawan.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '10000', 'fasilitas' => 'Parkir, Musholla, Gazebo',  'akses' => 'Motor, Mobil, Mobil Elf'],
            ['nama_wisata' => 'Pemandian Tasnan Baru', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 2, 'gambar' => 'tasnan_baru.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '10000', 'fasilitas' => 'Parkir, Musholla, Toilet, Tempat Makan, Penginapan',  'akses' => 'Motor, Mobil, Mobil Elf, Bus'],
            ['nama_wisata' => 'Kolam Renang Al- Amin', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 2, 'gambar' => 'kolam_renang_alamin.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '5000', 'fasilitas' => 'Parkir, Musholla, Toilet, Tempat Makan, Penginapan',  'akses' => 'Motor, Mobil, Mobil Elf,Bus'],
            ['nama_wisata' => 'Kolam Renang WOW Putra Demang', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 2, 'gambar' => 'kolam_renang_wow.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '7500', 'fasilitas' => 'Parkir, Musholla, Toilet, Tempat Makan, Penginapan',  'akses' => 'Motor, Mobil, Mobil Elf'],
            ['nama_wisata' => 'Wisata Bukit Luwih', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 2, 'gambar' => 'bukit_luwih.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '5000', 'fasilitas' => 'Parkir, Musholla, Toilet, Tempat Makan, Penginapan',  'akses' => 'Motor, Mobil, Mobil Elf'],
            ['nama_wisata' => 'Navara Waterpark', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 2, 'gambar' => 'navara_waterpark.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '10000', 'fasilitas' => 'Parkir, Musholla, Toilet, Gazebo, Tempat Makan, Penginapan',  'akses' => 'Motor, Mobil, Mobil Elf, Bus'],
            ['nama_wisata' => 'Wisata Teduh Glamping', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 2, 'gambar' => 'teduh_glamping.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '5000', 'fasilitas' => 'Parkir, Musholla, Toilet, Gazebo, Penginapan',  'akses' => 'Motor, Mobil, Mobil Elf, Bus'],
            ['nama_wisata' => 'Wisata Desa Agrapana Sumber Kalong', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 2, 'gambar' => 'desa_agrapana.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '5000', 'fasilitas' => 'Parkir, Musholla, Toilet, Gazebo, Spot Foto',  'akses' => 'Motor, Mobil, Mobil Elf'],
            ['nama_wisata' => 'Adua Waterpark', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 2, 'gambar' => 'adua_waterpark.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '10000', 'fasilitas' => 'Parkir, Musholla, Toilet, Tempat Makan, Penginapan',  'akses' => 'Motor, Mobil, Mobil Elf, Bus'],
            ['nama_wisata' => 'Makam Ki Ronggo', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 3, 'gambar' => 'makam_ki_ronggo.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '5000', 'fasilitas' => 'Parkir, Toilet, Musholla, Tempat Makan',  'akses' => 'Motor, Mobil, Mobil Elf, Bus'],
            ['nama_wisata' => 'Makam Kiai Mas Prajekan', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 3, 'gambar' => 'makam_kiai_mas.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '5000', 'fasilitas' => 'Parkir, Toilet, Musholla',  'akses' => 'Motor, Mobil, Mobil Elf, Bus'],
            ['nama_wisata' => 'Museum Kereta Api Bondowoso', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 3, 'gambar' => 'museum_kereta_api.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '0', 'fasilitas' => 'Parkir, Musholla, Toilet, Papan Informasi',  'akses' => 'Motor, Mobil, Mobil Elf, Bus'],
            ['nama_wisata' => 'Padepokan Seni Gema Buana', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 3, 'gambar' => 'padepokan_seni.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '3000', 'fasilitas' => 'Parkir, Toilet, Musholla, Tempat Bermain',  'akses' => 'Motor, Mobil, Mobil Elf, Bus'],
            ['nama_wisata' => 'Pusat Informasi Megalit', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 3, 'gambar' => 'pusat_informasi_megalit.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '0', 'fasilitas' => 'Parkir, Toilet, Musholla, Gazebo, Tempat Bermain',  'akses' => 'Motor, Mobil, Mobil Elf, Bus'],
            ['nama_wisata' => 'Gua Butha Jirek Mas', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 3, 'gambar' => 'gua_butha_jirek_mas.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '10000', 'fasilitas' => 'Gazebo, Papan Informasi',  'akses' => 'Motor, Mobil, Mobil Elf'],
            ['nama_wisata' => 'Gua Butha Sumber Canting Kluncing', 'alamat' => 'Bondowoso', 'sub_kriteria_id' => 3, 'gambar' => 'gua_butha_sumber_canting.jpg', 'deskripsi' => null, 'jam_operasional' => '08.00-16.00', 'harga_tiket' => '10000', 'fasilitas' => 'Papan Informasi',  'akses' => 'Motor, Mobil, Mobil Elf'],
        ];

        $this->db->table('wisata')->insertBatch($wisata);
    }
}
